version: '3.7'

networks:
 api-net:
   name: api-net
   driver: bridge
   attachable: true

services:
  api-zookeeper:
    image: wurstmeister/zookeeper
    environment:
      TZ: Asia/Seoul
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    networks:
      api-net:
        aliases:
          - api-zookeeper
    restart: always
  api-kafka:
    image: wurstmeister/kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    networks:
      api-net:
        aliases:
          - api-kafka
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_IP}:${KAFKA_PORT}
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:${KAFKA_PORT}
      #KAFKA_LISTENERS: PLAINTEXT://:${KAFKA_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_IP}:${ZOOKEEPER_PORT}
      # KAFKA_ZOOKEEPER_CONNECT: api-zookeeper:${ZOOKEEPER_PORT}
      TZ: Asia/Seoul
      # KAFKA_CREATE_TOPICS: ""
    depends_on:
      - api-zookeeper
    restart: always
#  web:
#    container_name: web
#    image: XXXXX
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - XXXX=YYYY
#    ports:
#      - "19910:19910"
#    volumes:
#      - ./db:/db
#    networks:
#      api-net:
#        aliases:
#          - XXXX
#    depends_on:
#      - kafka
