CREATE USER PGDBA WITH ENCRYPTED PASSWORD 'asdfasdf11';
CREATE USER PGAPP WITH ENCRYPTED PASSWORD 'asdfasdf11';
CREATE DATABASE APIDB OWNER PGAPP ENCODING 'utf-8';
GRANT ALL PRIVILEGES ON DATABASE "APIDB" TO PGAPP WITH GRANT OPTION;
DROP TABLE IF EXISTS "API_USER";
CREATE TABLE IF NOT EXISTS "API_USER"(
  EMP_NO VARCHAR(9),
  PWD VARCHAR(24),
  MBPHN_NO VARCHAR(24),
  EMP_NM VARCHAR(50),
  SECE_YN VARCHAR(1),
  PRIMARY KEY(EMP_NO)
);
DROP TABLE IF EXISTS "API_BATCH";
CREATE TABLE IF NOT EXISTS "API_BATCH"(
  BAT_ID VARCHAR(50),
  BAT_NM VARCHAR(100),
  PRCS_EXPLN VARCHAR(1000),
  ST_TPLG_ID VARCHAR(50),
  WRTR_EMP_NO VARCHAR(9),
  WRT_DT_TM DATE,
  CHG_DT_TM DATE,
  USE_YN VARCHAR(1),
  PRIMARY KEY(BAT_ID)
);